Check for openssl

diff --git a/.github/actions/build-macos/action.yml b/.github/actions/build-macos/action.yml
--- a/.github/actions/build-macos/action.yml
+++ b/.github/actions/build-macos/action.yml
@@ -3,6 +3,20 @@ description: 'Build ths packages for MACOS package'
 runs:
   using: "composite"
   steps:
+    - name: Check if OpenSSL is installed
+      shell: bash
+      run: |
+        if ! command -v openssl &> /dev/null
+        then
+          echo "OpenSSL could not be found, proceeding with installation."
+          mkdir openssl
+          cd openssl
+          curl -L -o openssl.tar.gz https://www.openssl.org/source/openssl-3.4.1.tar.gz
+          tar -xvzf openssl.tar.gz --strip-components=1
+        else
+          echo "OpenSSL is already installed."
+        fi
+
     - name: Xerces-C - prepare
       shell: bash
       run: |
